name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Test
        run: npm run test --if-present
      - name: Lint
        run: npm run lint  --if-present
      - name: Build
        run: npm run build --if-present
